name: Deploy Website to S3

on:
  push:
    branches:
      - main  # GitHub uses 'main' by default now

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'voting-system-task'
          AWS_ACCESS_KEY_ID: ${{ secrets.VOTING_SYSTEM_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.VOTING_SYSTEM_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
          SOURCE_DIR: './'
